apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gb0xths89-go 
  janus-idp.io/tekton: gb0xths89-go
  backstage.io/kubernetes-id: gb0xths89-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gb0xths89-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml