apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gb0xths89-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gb0xths89-go 
  name: gb0xths89-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gb0xths89-go 
